### ISSUE TITLE
Python2 EOL

### ISSUE THREAD

**Issue by francium** [beasley-weather/bbg#1]
Python2 will be reaching EOL in 2020. 3 years from now. Should we be using Python3 for all of our Python code?

data-generator is already written in Python3.

In this case, porting to 3 is not a huge issue, but we should be consistent throughout the project unless there is a very strong reason to use 2 (unsupported module/library for example).

**Comment by KyleArscott15** [comment]
I scripted in whatever I had. I'll port it to Python 3: no biggie.
